theme: minima
title: Titel aus der Configyaml
author: Autor
email: meineAdresse@bladasdlads234.de
description: > # this means to ignore newlines until "baseurl:"
 Das ist die erste Zeile der Testbeschreibung
 Das die Zweite
 
remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5" 
search: true
search_full_content: true



baseurl: /
# social links

github_username:  fundinawi # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

navigation_pages:
 - about.md
