theme: minima
title: Titel aus der Configyaml
author: Autor
email: meineAdresse@bladasdlads234.de
description: > # this means to ignore newlines until "baseurl:"
Das ist die erste Zeile der Testbeschreibung
Das die Zweite

# social links

github_username:  fundinawi # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
